<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mannequin">

	<!-- Body and weight measurements come from "Kodak's Ergonomic Design for People at Work" 50th percentile woman -->
	
    <!-- Puts mannequin in Gazebo sim -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/mannequin</robotNamespace>
        </plugin>
    </gazebo>

    <!-- * * * Link Definitions * * * -->
    <link name="base_link"> <!-- Base link is used to allow all body parts to have inertial settings -->
        <visual>
            <origin rpy="0.1 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                
                <box size="0.5 0.5 1"/>
            </geometry>
        </collision>
	</link>
    <gazebo reference="base_link">
        <kp>10000.0</kp>
        <kd>10000.0</kd>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/White</material>
    </gazebo>
    
    
    <link name="lower_body_link">
    	<visual>
            <origin rpy="0.0 0 0" xyz="0 0 0"/>
            <geometry>
                <!-- Material color set to white in blender -->
                <mesh filename="package://mannequin/models/mannequin/meshes/lower_body_formatted.dae"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://mannequin/models/mannequin/meshes/lower_body_low_poly.dae"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.145" rpy="0 0 0"/>
            <mass value="15.3" />
            <inertia ixx="0.2913375" ixy="0.0" ixz="0.0" iyy="0.162920775" iyz="0.0" izz="0.239803275"/>
        </inertial>
	</link>
    <gazebo reference="lower_body_link">
        <kp>5000.0</kp> 
        <kd>5000.0</kd>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/White</material>
    </gazebo>

	<link name="upper_body_link">
    	<visual>
            <origin rpy="0.0 0 0" xyz="0 0 0"/>
            <geometry>
                <!-- Material color set to white in blender -->
                <mesh filename="package://mannequin/models/mannequin/meshes/upper_body_formatted.dae"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://mannequin/models/mannequin/meshes/upper_body_low_poly.dae"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.145" rpy="0 0 0"/>
            <mass value="15.3" />
            <inertia ixx="0.2913375" ixy="0.0" ixz="0.0" iyy="0.162920775" iyz="0.0" izz="0.239803275"/>
        </inertial>
	</link>
    <gazebo reference="upper_body_link">
        <kp>5000.0</kp> 
        <kd>5000.0</kd>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/White</material>
    </gazebo>
    
    <!-- Torso Joint definitions -->
    <joint name="base_joint" type="fixed">
    	<parent link="base_link"/>
        <child link="lower_body_link"/>
    </joint>
    <joint name="torso_mid_joint" type="revolute">
        <parent link="lower_body_link"/>
        <child link="upper_body_link"/>
        <axis xyz="1 0 0"/> <!-- As is, the mannequin torso can only bend side to side, as this is what I have ROM data on-->
        <limit lower="-0.611" upper="0.611" effort="2" velocity="1.0"/>
        <origin xyz="0 0.01 0.207" rpy="0 0 0"/>
    </joint>
    
    
    <!-- Macro and variables for creating the arms -->
    <xacro:property name="pseudo_radius" value="0.01"/>
    <xacro:property name="pseudo_mass" value="0.01"/>
    <xacro:property name="pseudo_I" value="4e-07"/>
    <xacro:property name="arm_vertical_offset" value="0.287"/>
    <xacro:property name="arm_horizontal_offset" value="0.152"/>
    <xacro:macro name="arm" params="side reflection">
    
    	<!-- Shoulder and upper arm definitions-->
    	<!-- "invisible" links that add DOF to the shoulder -->
    	<link name="${side}_shoulder_roll_link">
    		<visual>
		        <origin rpy="0 0 0" xyz="0 0 0"/>
		        <geometry>
		            <sphere radius="${pseudo_radius}"/>
		        </geometry>
		    </visual>
		    <inertial>
		        <origin xyz="0 0 0" rpy="0 0 0"/>
		        <mass value="${pseudo_mass}" />
		        <inertia ixx="${pseudo_I}" ixy="0.0" ixz="0.0" iyy="${pseudo_I}" iyz="0.0" izz="${pseudo_I}"/>
		    </inertial>
    	</link>
    	<gazebo reference="${side}_shoulder_roll_link">
		    <kp>1000.0</kp>
		    <kd>1000.0</kd>
		    <mu1>10.0</mu1>
		    <mu2>10.0</mu2>
		    <material>Gazebo/Red</material>
		</gazebo>
    	<link name="${side}_shoulder_pitch_link">
    		<visual>
		        <origin rpy="0 0 0" xyz="0 0 0"/>
		        <geometry>
		            <sphere radius="${pseudo_radius}"/>
		        </geometry>
		    </visual>
		    <inertial>
		        <origin xyz="0 0 0" rpy="0 0 0"/>
		        <mass value="${pseudo_mass}" />
		        <inertia ixx="${pseudo_I}" ixy="0.0" ixz="0.0" iyy="${pseudo_I}" iyz="0.0" izz="${pseudo_I}"/>
		    </inertial>
    	</link>
    	<gazebo reference="${side}_shoulder_pitch_link">
		    <kp>1000.0</kp>
		    <kd>1000.0</kd>
		    <mu1>10.0</mu1>
		    <mu2>10.0</mu2>
		    <material>Gazebo/Green</material>
		</gazebo>
    	<link name="${side}_shoulder_yaw_link">
    		<visual>
		        <origin rpy="0 0 0" xyz="0 0 0"/>
		        <geometry>
		            <sphere radius="${pseudo_radius}"/>
		        </geometry>
		    </visual>
		    <inertial>
		        <origin xyz="0 0 0" rpy="0 0 0"/>
		        <mass value="${pseudo_mass}" />
		        <inertia ixx="${pseudo_I}" ixy="0.0" ixz="0.0" iyy="${pseudo_I}" iyz="0.0" izz="${pseudo_I}"/>
		    </inertial>
    	</link>
    	<gazebo reference="${side}_shoulder_yaw_link">
		    <kp>1000.0</kp>
		    <kd>1000.0</kd>
		    <mu1>10.0</mu1>
		    <mu2>10.0</mu2>
		    <material>Gazebo/Blue</material>
		</gazebo>
		<link name="${side}_upper_arm_link">
			<visual>
		        <origin rpy="0.0 0 0" xyz="0 0 0"/>
		        <geometry>
		            <!-- Material color set to white in blender -->
		            <mesh filename="package://mannequin/models/mannequin/meshes/upper_arm_formatted.dae"/>
		        </geometry>
		    </visual>
		    <collision>
		        <origin xyz="0 0 -0.170" rpy="0 0 0"/>
		        <geometry>
		            <cylinder radius="0.042" length="0.341"/>
		        </geometry>
		    </collision>
		    <inertial>
		        <origin xyz="0 0 -0.170" rpy="0 0 0"/>
		        <mass value="2.1" />
		        <inertia ixx="0.021275275" ixy="0.0" ixz="0.0" iyy="0.021275275" iyz="0.0" izz="0.0018522"/>
		    </inertial>
		</link>
		<gazebo reference="${side}_upper_arm_link">
		    <kp>5000.0</kp> 
		    <kd>5000.0</kd>
		    <mu1>10.0</mu1>
		    <mu2>10.0</mu2>
		    <material>Gazebo/White</material>
		</gazebo>
		
		<joint name="${side}_shoulder_roll_joint" type="revolute">
		    <parent link="upper_body_link"/>
		    <child link="${side}_shoulder_roll_link"/>
		    <axis xyz="1 0 0"/>
		    <limit lower="-1.05" upper="3.14" effort="2" velocity="1.0"/>
		    <origin xyz="0 ${arm_horizontal_offset * reflection} ${arm_vertical_offset}" rpy="0 0 0"/>
		</joint>
		<joint name="${side}_shoulder_pitch_joint" type="revolute">
		    <parent link="${side}_shoulder_roll_link"/>
		    <child link="${side}_shoulder_pitch_link"/>
		    <axis xyz="0 ${reflection} 0"/>
		    <limit lower="-1.3" upper="3.14" effort="2" velocity="1.0"/>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		</joint>
		<joint name="${side}_shoulder_yaw_joint" type="revolute">
		    <parent link="${side}_shoulder_pitch_link"/>
		    <child link="${side}_shoulder_yaw_link"/>
		    <axis xyz="0 0 ${reflection}"/>
		    <limit lower="-1.0" upper="1.5" effort="2" velocity="1.0"/>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		</joint>
		<joint name="${side}_upper_arm_joint" type="fixed">
		    <parent link="${side}_shoulder_yaw_link"/>
		    <child link="${side}_upper_arm_link"/>
		</joint>
		
		
		<!-- "Invisible" links for DOF of the elbow (flexion/extension[-0.17,2.62] and supination/pronation[-1.40,1.40]) -->
		<link name="${side}_elbow_flexion_link">
    		<visual>
		        <origin rpy="0 0 0" xyz="0 0 0"/>
		        <geometry>
		            <sphere radius="${pseudo_radius}"/>
		        </geometry>
		    </visual>
		    <inertial>
		        <origin xyz="0 0 0" rpy="0 0 0"/>
		        <mass value="${pseudo_mass}" />
		        <inertia ixx="${pseudo_I}" ixy="0.0" ixz="0.0" iyy="${pseudo_I}" iyz="0.0" izz="${pseudo_I}"/>
		    </inertial>
    	</link>
    	<gazebo reference="${side}_elbow_flexion_link">
		    <kp>1000.0</kp>
		    <kd>1000.0</kd>
		    <mu1>10.0</mu1>
		    <mu2>10.0</mu2>
		    <material>Gazebo/Red</material>
		</gazebo>
    	<link name="${side}_elbow_pronation_link">
    		<visual>
		        <origin rpy="0 0 0" xyz="0 0 0"/>
		        <geometry>
		            <sphere radius="${pseudo_radius}"/>
		        </geometry>
		    </visual>
		    <inertial>
		        <origin xyz="0 0 0" rpy="0 0 0"/>
		        <mass value="${pseudo_mass}" />
		        <inertia ixx="${pseudo_I}" ixy="0.0" ixz="0.0" iyy="${pseudo_I}" iyz="0.0" izz="${pseudo_I}"/>
		    </inertial>
    	</link>
    	<gazebo reference="${side}_elbow_pronation_link">
		    <kp>1000.0</kp>
		    <kd>1000.0</kd>
		    <mu1>10.0</mu1>
		    <mu2>10.0</mu2>
		    <material>Gazebo/Green</material>
		</gazebo>
		<link name="${side}_lower_arm_link">
			<visual>
		        <origin rpy="0.0 0 0" xyz="0 0 0"/>
		        <geometry>
		            <!-- Material color set to white in blender -->
		            <mesh filename="package://mannequin/models/mannequin/meshes/lower_arm_formatted.dae"/>
		        </geometry>
		    </visual>
		    <collision>
		        <origin xyz="0 0 -0.128" rpy="0 0 0"/>
		        <geometry>
		            <cylinder radius="0.035" length="0.256"/>
		        </geometry>
		    </collision>
		    <inertial>
		        <origin xyz="0 0 -0.128" rpy="0 0 0"/>
		        <mass value="2.1" />
		        <inertia ixx="0.01038165" ixy="0.0" ixz="0.0" iyy="0.01038165" iyz="0.0" izz="0.0011025"/>
		    </inertial>
		</link>
		<gazebo reference="${side}_lower_arm_link">
		    <kp>5000.0</kp> 
		    <kd>5000.0</kd>
		    <mu1>10.0</mu1>
		    <mu2>10.0</mu2>
		    <material>Gazebo/White</material>
		</gazebo>
		<joint name="${side}_elbow_flexion_joint" type="revolute">
		    <parent link="${side}_upper_arm_link"/>
		    <child link="${side}_elbow_flexion_link"/>
		    <axis xyz="1 0 0"/>
		    <limit lower="-1.05" upper="3.14" effort="2" velocity="1.0"/>
		    <origin xyz="0 0 ${-1 * arm_vertical_offset}" rpy="0 0 0"/>
		</joint>
		<joint name="${side}_elbow_pronation_joint" type="revolute">
		    <parent link="${side}_elbow_flexion_link"/>
		    <child link="${side}_elbow_pronation_link"/>
		    <axis xyz="0 ${reflection} 0"/>
		    <limit lower="-1.3" upper="3.14" effort="2" velocity="1.0"/>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		</joint>
		<joint name="${side}_lower_arm_joint" type="fixed">
		    <parent link="${side}_elbow_pronation_link"/>
		    <child link="${side}_lower_arm_link"/>
		</joint>
		
		<!-- Hand definitions -->
		<!-- Invisible links for flexion/extension and ulnar/radial deviation -->
		<link name="${side}_wrist_flexion_link">
    		<visual>
		        <origin rpy="0 0 0" xyz="0 0 0"/>
		        <geometry>
		            <sphere radius="${pseudo_radius}"/>
		        </geometry>
		    </visual>
		    <inertial>
		        <origin xyz="0 0 0" rpy="0 0 0"/>
		        <mass value="${pseudo_mass}" />
		        <inertia ixx="${pseudo_I}" ixy="0.0" ixz="0.0" iyy="${pseudo_I}" iyz="0.0" izz="${pseudo_I}"/>
		    </inertial>
    	</link>
    	<gazebo reference="${side}_wrist_flexion_link">
		    <kp>1000.0</kp>
		    <kd>1000.0</kd>
		    <mu1>10.0</mu1>
		    <mu2>10.0</mu2>
		    <material>Gazebo/Red</material>
		</gazebo>
		<link name="${side}_wrist_deviation_link">
    		<visual>
		        <origin rpy="0 0 0" xyz="0 0 0"/>
		        <geometry>
		            <sphere radius="${pseudo_radius}"/>
		        </geometry>
		    </visual>
		    <inertial>
		        <origin xyz="0 0 0" rpy="0 0 0"/>
		        <mass value="${pseudo_mass}" />
		        <inertia ixx="${pseudo_I}" ixy="0.0" ixz="0.0" iyy="${pseudo_I}" iyz="0.0" izz="${pseudo_I}"/>
		    </inertial>
    	</link>
    	<gazebo reference="${side}_wrist_deviation_link">
		    <kp>1000.0</kp>
		    <kd>1000.0</kd>
		    <mu1>10.0</mu1>
		    <mu2>10.0</mu2>
		    <material>Gazebo/Green</material>
		</gazebo>
		<link name="${side}_hand_link">
			<visual>
		        <origin rpy="0.0 0 0" xyz="0 0 0"/>
		        <geometry>
		            <!-- Material color set to white in blender -->
		            <mesh filename="package://mannequin/models/mannequin/meshes/hand_formatted.dae"/>
		        </geometry>
		    </visual>
		    <collision>
		        <origin xyz="0 0 0" rpy="0 0 0"/>
		        <geometry>
		            <box size="0.077 0.028 0.184"/>
		        </geometry>
		    </collision>
		    <inertial>
		        <origin xyz="0 0 -0.092" rpy="0 0 0"/>
		        <mass value="0.5" />
		        <inertia ixx="0.00144333333333" ixy="0.0" ixz="0.0" iyy="0.00165770833333" iyz="0.0" izz="0.000279708333333"/>
		    </inertial>
		</link>
		<gazebo reference="${side}_hand_link">
		    <kp>5000.0</kp> 
		    <kd>5000.0</kd>
		    <mu1>10.0</mu1>
		    <mu2>10.0</mu2>
		    <material>Gazebo/White</material>
		</gazebo>
		<joint name="${side}_wrist_flexion_joint" type="revolute">
		    <parent link="${side}_lower_arm_link"/>
		    <child link="${side}_wrist_flexion_link"/>
		    <axis xyz="1 0 0"/>
		    <limit lower="-1.05" upper="3.14" effort="2" velocity="1.0"/>
		    <origin xyz="0 0 -${arm_vertical_offset - 0.05}" rpy="0 0 0"/>
		</joint>
		<joint name="${side}_wrist_deviation_joint" type="revolute">
		    <parent link="${side}_wrist_flexion_link"/>
		    <child link="${side}_wrist_deviation_link"/>
		    <axis xyz="0 ${reflection} 0"/>
		    <limit lower="-1.3" upper="3.14" effort="2" velocity="1.0"/>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
		</joint>
		<joint name="${side}_hand_joint" type="fixed">
		    <parent link="${side}_wrist_deviation_link"/>
		    <child link="${side}_hand_link"/>
		</joint>
		
    	
    	<!-- ***** Actuator Definitions for arm ***** -->
    	<!-- Shoulder actuators -->
    	<transmission name="${side}shoulderrolltran">
		    <type>transmission_interface/SimpleTransmission</type>
		    <joint name="${side}_shoulder_roll_joint">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		    </joint>
		    <actuator name="${side}shoulderrollmotor">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		        <mechanicalReduction>1</mechanicalReduction>
		    </actuator>
		</transmission>
		<transmission name="${side}shoulderpitchtran">
		    <type>transmission_interface/SimpleTransmission</type>
		    <joint name="${side}_shoulder_pitch_joint">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		    </joint>
		    <actuator name="${side}shoulderpitchmotor">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		        <mechanicalReduction>1</mechanicalReduction>
		    </actuator>
		</transmission>
		<transmission name="${side}shoulderyawtran">
		    <type>transmission_interface/SimpleTransmission</type>
		    <joint name="${side}_shoulder_yaw_joint">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		    </joint>
		    <actuator name="${side}shoulderyawmotor">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		        <mechanicalReduction>1</mechanicalReduction>
		    </actuator>
		</transmission>
		
		
		<!-- Elbow actuators -->
		<transmission name="${side}elbowflexiontran">
		    <type>transmission_interface/SimpleTransmission</type>
		    <joint name="${side}_elbow_flexion_joint">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		    </joint>
		    <actuator name="${side}elbowflexionmotor">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		        <mechanicalReduction>1</mechanicalReduction>
		    </actuator>
		</transmission>
		<transmission name="${side}elbowpronationtran">
		    <type>transmission_interface/SimpleTransmission</type>
		    <joint name="${side}_elbow_pronation_joint">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		    </joint>
		    <actuator name="${side}elbowpronationmotor">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		        <mechanicalReduction>1</mechanicalReduction>
		    </actuator>
		</transmission>
		
		<!-- Wrist actuators -->
		<transmission name="${side}wristflexiontran">
		    <type>transmission_interface/SimpleTransmission</type>
		    <joint name="${side}_wrist_flexion_joint">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		    </joint>
		    <actuator name="${side}wristflexionmotor">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		        <mechanicalReduction>1</mechanicalReduction>
		    </actuator>
		</transmission>
		<transmission name="${side}wristdeviationtran">
		    <type>transmission_interface/SimpleTransmission</type>
		    <joint name="${side}_wrist_deviation_joint">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		    </joint>
		    <actuator name="${side}wristdeviationmotor">
		        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		        <mechanicalReduction>1</mechanicalReduction>
		    </actuator>
		</transmission>
    	
    </xacro:macro>
    
    <xacro:arm side="left" reflection="1"/>
    <xacro:arm side="right" reflection="-1"/>
    

</robot>
